import express, { Request, Response } from "express";
import { vehicalscontroller } from "./vehicals.controller";
import auth from "../../middleware/auth";
const router = express.Router();
router.post("/", auth("admin"), vehicalscontroller.PostVehicals);
router.get("/", vehicalscontroller.GetVehicals);
router.get("/:vehicleId", vehicalscontroller.GetSingleVehicals);
router.put("/:vehicleId", auth("admin"), vehicalscontroller.PutVehicals);
router.delete("/:vehicleId", auth("admin"), vehicalscontroller.DeletVehicals);
export const vehicalsrouter = router;
